// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPaWSVa8T64TGSvsvEPBP2MQfVFAVja8',
    appId: '1:326831698138:web:3fba221d698b2e1e27f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    authDomain: 'loginmovil-c3a75.firebaseapp.com',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    measurementId: 'G-408VKSNC5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrluJ2bHp7dVE4ReEy7ZU0H9BQYnphJz8',
    appId: '1:326831698138:android:643c25adacf2849427f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7yHxqjgf4MasJ6V7fSjR7v7QgyeEPyw',
    appId: '1:326831698138:ios:4e98d5692e65d75b27f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    androidClientId: '326831698138-ehmj8nfenqnlimrp9g0hvsnh1megs1st.apps.googleusercontent.com',
    iosClientId: '326831698138-jd425ln65acua7c7chaap1bnmn7g3e46.apps.googleusercontent.com',
    iosBundleId: 'com.example.asistenciaupeuFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD7yHxqjgf4MasJ6V7fSjR7v7QgyeEPyw',
    appId: '1:326831698138:ios:557c84e32b6aaf0b27f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    androidClientId: '326831698138-ehmj8nfenqnlimrp9g0hvsnh1megs1st.apps.googleusercontent.com',
    iosClientId: '326831698138-30l08rh43479cq6n1u2f4ordlrb0lq3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.asistenciaupeuFrontend.RunnerTests',
  );
}
