// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPaWSVa8T64TGSvsvEPBP2MQfVFAVja8',
    appId: '1:326831698138:web:3fba221d698b2e1e27f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    authDomain: 'loginmovil-c3a75.firebaseapp.com',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    measurementId: 'G-408VKSNC5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrluJ2bHp7dVE4ReEy7ZU0H9BQYnphJz8',
    appId: '1:326831698138:android:39ffc3c082a71c0b27f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7yHxqjgf4MasJ6V7fSjR7v7QgyeEPyw',
    appId: '1:326831698138:ios:b4cdde82b3d7852027f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    androidClientId: '326831698138-3uno3hocfrt81gvlhaf11gm83vf5blgt.apps.googleusercontent.com',
    iosClientId: '326831698138-gktkj1val5rao6u763gsasgtkh0rju9v.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD7yHxqjgf4MasJ6V7fSjR7v7QgyeEPyw',
    appId: '1:326831698138:ios:0366c64f4606064027f5e3',
    messagingSenderId: '326831698138',
    projectId: 'loginmovil-c3a75',
    storageBucket: 'loginmovil-c3a75.appspot.com',
    androidClientId: '326831698138-3uno3hocfrt81gvlhaf11gm83vf5blgt.apps.googleusercontent.com',
    iosClientId: '326831698138-hlseaeh9kkl9iptg41pi8mdgdbaf8lii.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
